requirejs(['../lib/config','js/config','../custom_functions/react_elements/config'],function(){
    requirejs(['js/build/Main'],function(Main){
        $(document).ready(function(){
            Main.iniciar('js/jogos/frutas.json');
            $('#novo-jogo').click(function(){
                Main.novoJogo();
            });
        });
    });
});