requirejs.config({
    "paths":{
        "jquery":"../bower_components/jquery/dist/jquery.min",
        "bootstrap":"../bower_components/bootstrap/dist/js/bootstrap.min",
        "lodash":"../bower_components/lodash/lodash.min",
        "react":"../bower_components/react/react",
        "array":"../custom_functions/array",
        "matriz":"../custom_functions/matriz",
        "string":"../custom_functions/string",
        "text":"../custom_functions/text",
        "mathlib":"../bower_components/MathLib/src/Math",
        "keys":"../custom_functions/keys",
        "uuid":"../custom_functions/uuid",
        "moment":"../bower_components/moment/min/moment.min"
    },
    "shim":{
        "bootstrap":{
            deps:["jquery"]
        }
    }
});